version: '3'
services:
  php-fpm:
    build: ./php
    image: greedying/php-fpm
    container_name: greedying-php-fpm
    volumes:
      - ./php/codes:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini:ro

  nginx:
    image: nginx:latest
    container_name: greedying-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 81:80
